app:
  micro:
    name: restaurant.order.order
server:
  error:
    include-binding-errors: always
    include-exception: true
    include-message: always
  port: ${app.port:10000}
spring:
  application:
    name: order
  config:
    import: configserver:http://127.0.0.1:8888
  datasource:
    driver-class-name: org.postgresql.Driver
    password: 123456
    url: jdbc:postgresql://localhost:5432/etiya
    username: postgres
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
  cloud:
    loadbalancer:
      retry:
        enabled: true
        retry-on-all-operations: true
        max-retries-on-next-service-instance: 3
        max-retries-on-same-service-instance: 0
resilience4j:
  retry:
    instances:
      myAccountRetry:
        wait-duration: '1ms'
        max-attempts: 3
        retry-exception-predicate: org.training.ms.etiya.msorder.services.integrations.RetryExceptionChoose
        result-predicate: org.training.ms.etiya.msorder.services.integrations.ReturnValRetryChoose
  circuitbreaker:
    instances:
      myAccountCB:
        sliding-window-type: count_based
        sliding-window-size: 20
        minimum-number-of-calls: 10
        failure-rate-threshold: 30
        wait-duration-in-open-state: '4s'
        automatic-transition-from-open-to-half-open-enabled: false
        permitted-number-of-calls-in-half-open-state: 5
        max-wait-duration-in-half-open-state: '10s'
        slow-call-rate-threshold: 70
        slow-call-duration-threshold: '200ms'
        register-health-indicator: true
        allow-health-indicator-to-fail: true

